USE [CaboodlePOC_Stage]

CREATE TABLE Custom.SXuErsatzStaffingEvent (
	StageKey INT IDENTITY(1, 1) --Technically optional
	,
	STAFFING_EVENT_ID NVARCHAR(50),
	[DATE] NVARCHAR(50),
	EMPLOYEE_ID NVARCHAR(50),
	EMPLOYEE_ROLE_ID NVARCHAR(50),
	HOURS_LOGGED NVARCHAR(50),
	LoadDate DATE
	)
