USE [CaboodlePOC_Stage]

CREATE TABLE Custom.SXu_ErsatzEmpolyeeRole (
	StageKey INT IDENTITY(1, 1) --Technically optional	
	,EMPLOYEE_ROLE_ID NVARCHAR(10)
	,EMPLOYEE_ROLE_NAME NVARCHAR(50)
	,EMPLOYEE_ROLE_DESCRIPTION NVARCHAR(300)
	,EMPLOYEE_CLASS NVARCHAR(100)
	,LoadDate DATE
	)
